run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - misspell
    - goimports
    - errcheck
    - staticcheck
    - unused
    - gosimple

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/pyshx/fake-batch-server

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

