version: '3.8'

services:
  fake-batch-server:
    build: .
    image: fake-batch-server:latest
    container_name: fake-batch-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - VERBOSE=false
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

